export const CART_ADD_PRODUCTS_REQUEST = "CART_ADD_PRODUCTS_REQUEST";
export const CART_ADD_PRODUCTS_SUCCESS = "CART_ADD_PRODUCTS_SUCCESS";
export const CART_ADD_PRODUCTS_FAIL = "CART_ADD_PRODUCTS_FAIL";

export const CART_REMOVE_PRODUCTS_REQUEST = "CART_REMOVE_PRODUCTS_REQUEST";
export const CART_REMOVE_PRODUCTS_SUCCESS = "CART_REMOVE_PRODUCTS_SUCCESS";
export const CART_REMOVE_PRODUCTS_FAIL = "CART_REMOVE_PRODUCTS_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const CART_SAVE_SHIPPING_INFO = "CART_SAVE_SHIPPING_INFO";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_CLEAR_PRODUCTS = "CART_CLEAR_PRODUCTS";
